# Generated by Django 5.1.3 on 2024-12-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_cadastroaluno_celular_alter_cadastroaluno_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treino_masculino_perder_peso', models.TextField()),
                ('treino_masculino_ganho_massa', models.TextField()),
                ('treino_feminino_perder_peso', models.TextField()),
                ('treino_feminino_ganho_massa', models.TextField()),
                ('treino_masculino_atleta', models.TextField()),
                ('treino_feminino_atleta', models.TextField()),
            ],
        ),
    ]
