# Generated by Django 5.1.3 on 2024-12-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_treino'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreinoAlunoCadastrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treino_personalizado_aluno', models.TextField()),
            ],
        ),
    ]
