# Generated by Django 5.1.3 on 2025-02-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_treinoalunocadastrado_aluno_cadastrado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PulicarAcademia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos-publicar-academia')),
                ('titulo', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
