# Generated by Django 5.1.3 on 2025-02-08 04:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_pulicaracademia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastroaluno',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
