# Generated by Django 5.1.6 on 2025-02-16 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_mensalidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensalidade',
            name='paga',
        ),
    ]
