# Generated by Django 5.1.6 on 2025-02-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_mensalidade_paga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalidade',
            name='data_pagamento',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
