# Generated by Django 5.1.6 on 2025-02-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_mensalidade_data_pagamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensalidade',
            old_name='data_pagamento',
            new_name='data_matricula',
        ),
    ]
