# Generated by Django 5.1.6 on 2025-02-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_rename_data_pagamento_mensalidade_data_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalidade',
            name='data_matricula',
            field=models.DateField(),
        ),
    ]
