# Generated by Django 5.1.6 on 2025-02-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_mensalidade_data_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalidade',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
