# Generated by Django 5.1.6 on 2025-02-26 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_nossosprodutos_alter_mensalidade_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nossosprodutos',
            old_name='mensagem',
            new_name='descricao',
        ),
    ]
