# Generated by Django 5.1.3 on 2024-12-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LadoDireito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.CharField(default='white', max_length=30)),
                ('titulo', models.CharField(default='Título Direito', max_length=100)),
                ('titulo_cor', models.CharField(default='black', max_length=30)),
                ('titulo_estilo_font', models.CharField(default='Arial', max_length=255)),
                ('titulo_fontSize', models.IntegerField(default=18)),
                ('texto', models.TextField(default='Texto do lado direito')),
                ('texto_cor', models.CharField(default='black', max_length=30)),
                ('texto_estilo_font', models.CharField(default='Arial', max_length=255)),
                ('texto_fontSize', models.IntegerField(default=14)),
            ],
        ),
        migrations.CreateModel(
            name='LadoEsquerdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.CharField(default='white', max_length=30)),
                ('titulo', models.CharField(default='Título Esquerdo', max_length=100)),
                ('titulo_cor', models.CharField(default='black', max_length=30)),
                ('titulo_estilo_font', models.CharField(default='Arial', max_length=255)),
                ('titulo_fontSize', models.IntegerField(default=18)),
                ('texto', models.TextField(default='Texto do lado esquerdo')),
                ('texto_cor', models.CharField(default='black', max_length=30)),
                ('texto_estilo_font', models.CharField(default='Arial', max_length=255)),
                ('texto_fontSize', models.IntegerField(default=14)),
            ],
        ),
        migrations.CreateModel(
            name='NavBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.CharField(default='black', max_length=30)),
                ('texto_cor', models.CharField(default='black', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NomeDampresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Minha Empresa', max_length=255)),
                ('estilo_font', models.CharField(default='Arial', max_length=100)),
                ('cor_titulo', models.CharField(default='black', max_length=30)),
                ('fontSize', models.IntegerField(default=16)),
            ],
        ),
    ]
