# Generated by Django 5.1.3 on 2024-12-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_ladodireito_titulo_cor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomeDaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Minha Empresa', max_length=255)),
                ('estilo_font', models.CharField(default='Arial', max_length=100)),
                ('cor_titulo', models.CharField(default='blue', max_length=30)),
                ('fontSize', models.IntegerField(default=16)),
            ],
        ),
        migrations.DeleteModel(
            name='NomeDampresa',
        ),
    ]
