# Generated by Django 5.1.3 on 2024-12-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_logobanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladoesquerdo',
            name='img_lado_direito',
            field=models.ImageField(default=2, upload_to='img_lado_direito'),
            preserve_default=False,
        ),
    ]
