# Generated by Django 5.1.3 on 2024-12-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_ladoesquerdo_img_lado_direito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ladoesquerdo',
            name='img_lado_direito',
        ),
        migrations.AddField(
            model_name='ladodireito',
            name='img_lado_direito',
            field=models.ImageField(default=2, upload_to='img_lado_direito'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ladoesquerdo',
            name='img_lado_esquerdo',
            field=models.ImageField(default=1, upload_to='img_lado_esquerdo'),
            preserve_default=False,
        ),
    ]
