# Generated by Django 5.1.3 on 2024-12-05 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_ladodireito_altura_ladodireito_largura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ladoesquerdo',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='ladoesquerdo',
            name='img_lado_esquerdo',
        ),
        migrations.RemoveField(
            model_name='ladoesquerdo',
            name='largura',
        ),
    ]
