# Generated by Django 5.1.3 on 2024-12-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_cadastroalunoonline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastroalunoonline',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='cadastroalunoonline',
            name='rua_av',
        ),
        migrations.AddField(
            model_name='cadastroalunoonline',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='cadastroalunoonline',
            name='password',
            field=models.CharField(default=1, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastroalunoonline',
            name='senha',
            field=models.CharField(default=(2,), max_length=128),
            preserve_default=False,
        ),
    ]
