# Generated by Django 5.1.3 on 2025-01-04 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_cadastroalunoonline_senha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CadastroAlunoOnLine',
        ),
    ]
